AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFormation Template for the URL shortener application

Parameters:
  Prefix:
    Description: The prefix to be attached to the names of each resource
    Type: String
    Default: url-shortener-iac

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref Prefix
              - vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref Prefix
              - subnet
              - public1
              - !Sub ${AWS::Region}a

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: !Sub ${AWS::Region}b
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref Prefix
              - subnet
              - public2
              - !Sub ${AWS::Region}b

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.128.0/20
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref Prefix
              - subnet
              - private1
              - !Sub ${AWS::Region}a

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.144.0/20
      AvailabilityZone: !Sub ${AWS::Region}b
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref Prefix
              - subnet
              - private2
              - !Sub ${AWS::Region}b
