basePath: /api/v1
definitions:
  models.LongUrl:
    properties:
      longUrl:
        type: string
    type: object
  models.Url:
    properties:
      id:
        type: integer
      longUrl:
        type: string
      shortUrl:
        type: string
    type: object
  utils.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a URL shortener service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: URL shortening API
  version: "1.0"
paths:
  /{shortUrl}:
    get:
      consumes:
      - application/json
      description: redirect shortened urls to the actual urls
      parameters:
      - description: Short URL
        in: path
        name: shortUrl
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: redirect shortened urls to the actual urls
      tags:
      - redirect
  /data/shorten:
    post:
      consumes:
      - application/json
      description: generate shortened urls
      parameters:
      - description: Add URL for shortening
        in: body
        name: longUrl
        required: true
        schema:
          $ref: '#/definitions/models.LongUrl'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Url'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: generate shortened urls
      tags:
      - example
swagger: "2.0"
